### ISSUE TITLE
EKS Tutorial questions

### ISSUE THREAD

**Issue by aggietallboy** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#211] opened 2023-06-12 17:36 UTC
Apologies as I'm still new to EKS and clusters as a whole.. but this tutorial has led to a lot of learning:

I have scripted the install into Amazon's EKS service, and after a lot of trial I have ONE interaction point -- unlocking the vault.

Error Logging In
![image](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/assets/10222174/0990e2de-1bc7-4e11-99ce-e06041cf2cef)

I've confirmed the username and password in the saved cluster secrets, and they're good

I've done kubectl get pods and then kubectl get logs xxxx for the mps server, webui.. but keep getting:
error: the server doesn't have a resource type "logs"

**Comment by bwendlandt-intel** [comment] 2023-06-12 18:13
Hello! The error can be caused by a number of things, some are detailed [in the Troubleshooting page](https://open-amt-cloud-toolkit.github.io/docs/2.11/Reference/troubleshooting/#why-cant-i-login-to-the-sample-web-ui).

The two most common are:
1. Did you accept the self-signed certificate warning when first visiting `https://{Your_Deployment_Server}`? You can also visit `https://{Your_Deployment_Server}:4433` and try to accept it there to verify you have before returning to login page and trying to log in.
2. Are all of your pods healthy? Was Vault successfully initialized and unsealed with the kv engine created?

<br>

In your output from `kubectl get pods`, are these all healthy and running?

The format for the command for retrieving logs with kubectl is slightly different.  It should be:
```
kubectl logs podName

// ex: kubectl logs mps-5f7455jrd5b-csytc

// You can also provide `-f` to follow them or `--tail={X}` where X is an int to retrieve X amount of rows back
```

**Comment by aggietallboy** [comment] 2023-06-14 12:25
I have accepted the certificate (chrome wouldn't let me see the page otherwise).
I have not been successful connecting to 4433 at all.

I have a rebuild running right now, and will post some more info

For the  logs, as I'd said I'm new to this -- kubectl logs <<podname>> not get logs 
I'm seeing database timeouts on mps/rps.

I'm testing the constructed db connect string and it seems ok.

I've got this all set up as a powershell script and self-contained directory bundle, and will be posting a feedback thread on some simplifications and automations I've been able to do.

**Comment by bwendlandt-intel** [comment] 2023-06-14 20:38
Clarifying question, is this based on trying to modify the deployment of DB to use SSL or the default, basic deployment our documentation walks through?

Can you please share what returns from `kubectl get pods`? If you cannot reach port 4433, then MPS must be unhealthy which could be caused if it's unable to reach the DB.

And of course, any feedback or changes you've found to make life easier for everyone is much, much appreciated!

**Comment by aggietallboy** [comment] 2023-06-15 02:56
I am starting out with the basic
I will be posting my powershell script very soon

Current response from 4433:

unexpectedly closed the connection.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_CLOSED

443 does what we expect in chrome
![image](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/assets/10222174/154bbfc4-1214-4580-8b69-1cbee73da251)

but we proceed anyway, and get to the login page as expected

still getting error logging in
mps and rtb are both reporting:

info: Index - waiting for db[2] ETIMEDOUT

**Comment by aggietallboy** [comment] 2023-06-15 02:58
in troubleshooting I have tested with ssl disabled for all three connections, with the mps and rps as no sslmode setting at all.

**Comment by aggietallboy** [comment] 2023-06-17 14:57
I noted in the db string thread that it was a security setting that needed to be adjusted.

**Comment by bwendlandt-intel** [comment] 2023-07-11 17:15
Closing this as resolved now.  Resolution details as to the script change and connection string can be found as part of issue #208 .  Thanks!

**Closed by bwendlandt-intel** 2023-07-11 17:15 UTC
Labels: question
