### ISSUE TITLE
Web Certificate Management

### ISSUE THREAD

**Issue by mlorenz1-lenovo** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#163] opened 2022-12-21 19:49 UTC
We are integrating our Solution with the toolkit and now we need to use our own custom certificates to secure all the communication. A self-signed certificate is being generated, by the API Gateway since we didn't add one, for all HTTPS/WSS communication in MPS/RPS, but we are having issues to provide our certificates to the toolkit. My question is: Is there a proper way to configure it in the Azure, API Gateway or even in the application (MPS) ?

**Comment by rsdmike** [comment] 2022-12-22 19:03
For configuring Kong, you can mount a `./certs` volume into the container with your private key and certificate and then add two ENV variables that point to those files that are mounted in. For example:

``` yaml
kong:
    image: kong:2.3
    environment:
      - KONG_SSL_CERT=/ssl/cert.crt
      - KONG_SSL_CERT_KEY=/ssl/key.pem
    volumes:
      - ./kong.yaml:/home/kong/kong.yml
      - ./certs:/ssl
```

**Comment by mlorenz1-lenovo** [comment] 2022-12-28 21:45
Sorry for the delayed response, doing this suggestion didn't work, but it led us to find that doing it using secrets and mounting a  volume in kubernetes worked well, so thank you for your response. Our next issue is with the certificates added in the domain section in the sample ui.
Basically in the toolkit versions 2.5, 2.6 and 2.7 some verifications are being done while we try to add a certificate generated by us that didn't happen in others versions (2.1 ~ 2.4). We received two different errors with two different certificates, the first one was "FQDN not associated with provisioning certificate: domainSuffix" with a certificate generated using openssl and the other one was basically saying that the password was wrong or the certificate was invalid, but the password was correct and the certificate was already used in some other provisions tests.

**Comment by graikhel-intel** [comment] 2023-01-03 19:16
Regarding "FQDN not associated with provisioning certificate: domainSuffix" – There was a fix to this issue in [v2.6 release](https://github.com/open-amt-cloud-toolkit/rps/commit/530a85057c1b28135cd350d551c84109a94b6036). Typically you would see this when “Common Name” on the Provisioning Certificate does not match with “Domain Name” on the Domain profile (in RPS). Could you please try the latest release i.e., v2.7 and see if the issue still persists?

Regarding “password was wrong or the certificate was invalid” – Since you've already tried/tested the provisioning certificate already, could you please send me/attach the logs of RPS? That’ll help us figure out the exact root cause

**Comment by mlorenz1-lenovo** [comment] 2023-01-04 21:04
We tested RPS in 2.7, 2.6 and 2.5 versions and still got the FQDN error. The certificate common name match the Domain Name in the Domain profile field.

About the RPS logs, we are gathering it and will provide ASAP.

**Comment by mlorenz1-lenovo** [comment] 2023-01-31 13:48
We tested again using a new deploy(v 2.7) and below are our findings:
* The same tls certificate used for kong, we used to create a domain profile and provision a machine, worked sucessfully, but this cert doesn't have the extensions(Oids) recommended and it was generated using openssl (just for testing purpose).
* We tried to create the domain profile using another tls certificate, but this one was generated with C# (that's the way we are using in our application) with all the extensions and Oids recommended to provision a machine. We couldn't create the domain profile, the sample ui returns the following error "Unable to decrypt provisioning certificate. Please check that the password is correct, and that the certificate is a valid certificate.: provisioningCertPassword".
* Even changing the extensions from the C# generated cert to become identical to the other one, the sample ui still threw the error above.
* Another weird behavior is that the user is allowed to add a invalid certificate when editing a domain profile. The steps are down below:
  1. We created the domain profile using our openssl generated tls cert.
  2. Edited the domain profile.
  3. uploaded the C# generated tls cert.
  4. Changed the domain suffix accordingly.
  5. Save

So, that being said, our question is, what are the validations done in the tls certificate object while a domain profile is created? we need to generate using C#, because that's how is built our application.

**Comment by bsilva7** [comment] 2023-02-20 21:13
Hello there,

As described by Lorenzi, only certificates generated by our app without a private key are accepted by the Toolkit when creating a new Domain. However, when uploading a certificate with a private key and issued by a trust CA, the Domain is created successfully.

Could you please help us to figure out why this certificate with a private key is not being accepted by the toolkit?

The leafCert.pfx file attached is a test certificate generated with a private key and not accepted by the toolkit.
![image](https://user-images.githubusercontent.com/121193943/220199095-19d5b8eb-7bb5-45d2-a410-0b3c39ef6cba.png)

The leafCert1.pfx file attached is a test certificate generated without a private key and was accepted by the toolkit.
[leafCerts.zip](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/files/10787779/leafCerts.zip)

The password for both test certificates is "fit123".

**Comment by graikhel-intel** [comment] 2023-02-21 17:05
Thank you for attaching the pfx. Will take a look at the pfx and get back to you.

**Comment by graikhel-intel** [comment] 2023-02-22 21:23
I noticed that RPS was throwing "Error: Unparsed DER bytes remain after ASN.1 parsing" exception when decoding leafCert.pfx file. We use [node-forge](https://www.npmjs.com/package/node-forge) for decoding/decrypting PFX and seems like there was a change with respect to how they decrypt PFX from version 1.3. Found some information about the change here https://github.com/digitalbazaar/forge/issues/975

I have a potential fix available here https://github.com/open-amt-cloud-toolkit/rps/tree/fix_domaincert_issue. Wanted your help with validation to make sure this fix is working. 

To test this fix, you will need to 
1. Pull code from fix_domaincert_issue branch under rps repository
2. Build a new RPS image 
3. Deploy RPS container (don't have to redeploy any other containers)
4. Check if you are able to create a domain profile (using PFX that contains the private key)

Just a note, I tested creating a domain profile with leafCert.pfx you've attached and looks like it worked.

**Comment by bsilva7** [comment] 2023-02-22 22:36
Oh, great!! I'll ask the team to execute these steps and I inform you as soon as I get the answer.
Thanks, Ganesh!

**Comment by graikhel-intel** [comment] 2023-03-13 22:56
@bsilva7 should I close this issue? I think we resolved the ACM activation/Provisioning certificates issues the last time we spoke.

**Comment by matt-primrose** [comment] 2023-04-12 15:53
Closing this issue due to no response from author.  If there is new information, please feel free to re-open the issue and provide the updated information.

**Closed by matt-primrose** 2023-04-12 15:53 UTC
Labels: investigate
